name: doc

# event type（此处我们选择 push，且仅当 push 到 master 分支触发）
on:
  push:
    branches:
      - main

# 任务列表
jobs:
  # 任务名称
  release:
    # 在何种平台执行，可选 windows-latest/ubuntu-latest/macOS-latest 等
    runs-on: ubuntu-latest

    # 为了加速构建，我们使用同一个包含 Node.js 的容器运行所有命令
    container:
      image: thonatos/github-actions-nodejs

    # 这里定义了任务运行过程中的各个步骤
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
      - name: PUB
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PUB_KEY }}
          name: id_ed25519.pub
          known_hosts: unnecessary
          config: |
            Host bastion
              # HostName xxx.xxx.xxx.xxx
              # User user-of-bastion
              IdentityFile ~/.ssh/id_ed25519.pub
      - name: PRIVATE
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: unnecessary
          config: |                                         # will be appended to existing .ssh/config
            Host target
              # HostName yyy.yyy.yyy.yyy
              # User user-of-target
              IdentityFile ~/.ssh/id_ed25519
              # ProxyCommand ssh -W %h:%p bastion

      # 环境
      - run: |
          npm -v
          node -v
          yarn -v
          git config --global user.email "zhujiawei@guanmai.cn"
          git config --global user.name "jawei"
          git config --global url.ssh://git@code.guanmai.cn/.insteadOf https://code.guanmai.cn/
      - run: |
          pwd
          git clone https://github.com/jaweii/ci-test.git
      - run: |
          cd ci-test
          npm install git+https://code.guanmai.cn/fe-x/gm_api.git#79aa5ce2bc952a93c0e6a98c58c7ab547f9bcb32
